import { z } from "zod";

/**
 * The portable CodeType guided session config.
 *
 * Designed to be:
 *   - generated by an external LLM
 *   - edited by hand
 *   - shared
 *   - bundled as a curated session
 *
 * Validation is strict everywhere: unknown fields are rejected at the
 * top level and inside each item, so typos like `paths` instead of
 * `path` get surfaced immediately rather than silently dropped. Cross-
 * field rules (symbol-OR-range, startLine <= endLine) live in
 * `validateConfig` so we can surface friendly per-item errors.
 */

const NonEmptyString = z.string().min(1);

const FileItem = z
  .object({
    level: z.literal("file"),
    path: NonEmptyString,
    label: NonEmptyString,
    startLine: z.number().int().positive().optional(),
    endLine: z.number().int().positive().optional(),
  })
  .strict();

const ClassItem = z
  .object({
    level: z.literal("class"),
    path: NonEmptyString,
    symbol: NonEmptyString.optional(),
    label: NonEmptyString,
    startLine: z.number().int().positive().optional(),
    endLine: z.number().int().positive().optional(),
  })
  .strict();

const FunctionItem = z
  .object({
    level: z.literal("function"),
    path: NonEmptyString,
    symbol: NonEmptyString.optional(),
    label: NonEmptyString,
    startLine: z.number().int().positive().optional(),
    endLine: z.number().int().positive().optional(),
  })
  .strict();

export const PracticeItemSchema = z.discriminatedUnion("level", [
  FileItem,
  ClassItem,
  FunctionItem,
]);

export const CodeTypeConfigSchema = z
  .object({
    version: z.literal(1),
    repo: NonEmptyString.regex(
      /^[A-Za-z0-9_.][A-Za-z0-9_.\-]*\/[A-Za-z0-9_.][A-Za-z0-9_.\-]*$/,
      "Expected owner/repo",
    ),
    ref: z.string().optional(),
    title: NonEmptyString,
    description: z.string().optional(),
    /**
     * Default `"tidbits"` clips every item to a short navigation-friendly
     * window. Set to `"off"` to type full files / full symbol bodies as
     * authored — useful when the user specifically asks the LLM for full
     * files instead of a navigation tour.
     */
    clip: z.enum(["tidbits", "off"]).optional(),
    items: z.array(PracticeItemSchema).min(1, "At least one item is required"),
  })
  .strict();

export type CodeTypeConfig = z.infer<typeof CodeTypeConfigSchema>;
export type PracticeItem = z.infer<typeof PracticeItemSchema>;

export type ItemValidationError = {
  index: number;
  path: string[];
  message: string;
};

export type ValidateResult =
  | { ok: true; value: CodeTypeConfig }
  | { ok: false; parseError?: string; errors: ItemValidationError[] };

/**
 * Validate raw JSON text. Returns either a typed config or a list of
 * human-readable errors keyed by item index where possible.
 */
export function validateConfigText(raw: string): ValidateResult {
  let json: unknown;
  try {
    json = JSON.parse(raw);
  } catch (e) {
    return {
      ok: false,
      errors: [],
      parseError:
        e instanceof Error ? friendlyJsonError(e.message) : "Invalid JSON",
    };
  }
  return validateConfig(json);
}

export function validateConfig(json: unknown): ValidateResult {
  const parsed = CodeTypeConfigSchema.safeParse(json);
  if (!parsed.success) {
    const errors: ItemValidationError[] = parsed.error.issues.map((issue) => {
      const path = issue.path.map(String);
      const idxStr = path[0] === "items" ? path[1] : undefined;
      const idx = idxStr !== undefined ? Number(idxStr) : -1;
      return {
        index: Number.isInteger(idx) ? idx : -1,
        path,
        message: humanizeIssue(issue.message),
      };
    });
    return { ok: false, errors };
  }
  // Cross-field rule: function/class items must have symbol OR line range.
  const extra: ItemValidationError[] = [];
  parsed.data.items.forEach((it, i) => {
    if (it.level === "file") return;
    const hasSymbol = "symbol" in it && typeof it.symbol === "string";
    const hasRange =
      typeof it.startLine === "number" && typeof it.endLine === "number";
    if (!hasSymbol && !hasRange) {
      extra.push({
        index: i,
        path: ["items", String(i)],
        message: `${it.level} item needs a symbol name OR startLine + endLine`,
      });
    }
    if (
      typeof it.startLine === "number" &&
      typeof it.endLine === "number" &&
      it.startLine > it.endLine
    ) {
      extra.push({
        index: i,
        path: ["items", String(i), "endLine"],
        message: `endLine (${it.endLine}) must be greater than or equal to startLine (${it.startLine})`,
      });
    }
  });
  if (extra.length) return { ok: false, errors: extra };
  return { ok: true, value: parsed.data };
}

function humanizeIssue(message: string): string {
  if (message === "Required") return "is required";
  if (message === "Expected number, received undefined") return "is required";
  if (message.startsWith("Invalid literal value, expected")) {
    return message.replace("Invalid literal value, expected", "must equal");
  }
  if (message.startsWith("String must contain at least 1 character")) {
    return "is required";
  }
  if (message.startsWith("Invalid discriminator value")) {
    return message.replace(
      "Invalid discriminator value. Expected",
      "level must be one of",
    );
  }
  if (message.startsWith("Unrecognized key")) {
    return message.replace("Unrecognized key(s) in object: ", "unknown field ");
  }
  return message;
}

function friendlyJsonError(msg: string): string {
  // Try to extract a line/column from "Unexpected token } in JSON at position 42"
  const m = msg.match(/position (\d+)/);
  if (m) return `Invalid JSON near position ${m[1]}`;
  return msg.replace(/^SyntaxError:\s*/, "");
}

export function describeItem(item: PracticeItem): string {
  if (item.level === "file") return item.path;
  const sym = "symbol" in item && item.symbol ? `·${item.symbol}` : "";
  return `${item.path}${sym}`;
}

export function summarizeItems(items: PracticeItem[]) {
  let files = 0;
  let functions = 0;
  let classes = 0;
  for (const it of items) {
    if (it.level === "file") files++;
    else if (it.level === "function") functions++;
    else classes++;
  }
  return { total: items.length, files, functions, classes };
}
